<a href="https://colab.research.google.com/github/stanley1208/AI-Learning/blob/main/week1_day5_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np


a=np.array([1,2,3])
b=np.array([4,5,6])
print("a+b=",a+b)
print("a*b=",a*b)


a+b= [5 7 9]
a*b= [ 4 10 18]


In [3]:
matrix=np.array([[1,2,3],
                 [4,5,6]])
print("Shape:",matrix.shape)
print("Transpose:",matrix.T)



Shape: (2, 3)
Transpose: [[1 4]
 [2 5]
 [3 6]]


In [5]:
z=np.zeros((2,3))
r=np.random.rand(2,3)
print("Zeros:\n",z)
print("Random:\n",r)

Zeros:
 [[0. 0. 0.]
 [0. 0. 0.]]
Random:
 [[0.24506086 0.97209791 0.59033137]
 [0.89170969 0.60351543 0.8219558 ]]


In [7]:
data=np.array([10,20,30,40])
print("Mean:", data.mean())
print("std:",data.std())
print("Normalize:",data-data.mean()/data.std())

Mean: 25.0
std: 11.180339887498949
Normalize: [ 7.76393202 17.76393202 27.76393202 37.76393202]
